### ISSUE TITLE
Compose building

### ISSUE THREAD

**Issue by ImPedro29** [polkascan/explorer-api#1]
When i run `docker-compose up --build`

is retuning
```bash
Collecting git+https://github.com/matthijsb/sqlalchemy-pagination.git (from -r requirements.txt (line 20))
  Cloning https://github.com/matthijsb/sqlalchemy-pagination.git to /tmp/pip-req-build-4bsh1upb
  Running command git clone -q https://github.com/matthijsb/sqlalchemy-pagination.git /tmp/pip-req-build-4bsh1upb
  Resolved https://github.com/matthijsb/sqlalchemy-pagination.git to commit 636f872d75e5c5346f903910b7c02430c47c9be0
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4bsh1upb/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4bsh1upb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qe2e2bzl
         cwd: /tmp/pip-req-build-4bsh1upb/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4bsh1upb/setup.py", line 39, in <module>
        tests_require=requirements('requirements-dev.txt'),
      File "/tmp/pip-req-build-4bsh1upb/setup.py", line 13, in requirements
        return [str(r.req) for r in reqs]
      File "/tmp/pip-req-build-4bsh1upb/setup.py", line 13, in <listcomp>
        return [str(r.req) for r in reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
WARNING: Discarding git+https://github.com/matthijsb/sqlalchemy-pagination.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Building Api

**Comment by matthijsb** [comment]
There seems to be an error in the build wheel.. For now the build error can be temporarily ignored, as it's functionality should work even with the build error. It will be replaced with proper pagination when i return back from vacation. (This pagination library was added as a quick fix for team polkascan-explorer, since they needed pagination for their tests and there was an issue with the original keyset pagination in combination with mysql).
