### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by arjanz** [polkascan/explorer-api#19]
https://explorer-dev.polkascan.io/polkadot/account/1qnJN7FViy3HZaxZK9tGAA71zxHSBeUweirKqCaox4t8GT7

Raises the following exception in the API:

```
explorer-v3-api-polkadot_1      | An exception occurred in resolvers
explorer-v3-api-polkadot_1      | Traceback (most recent call last):
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/starlette_graphene3.py", line 360, in _observe_subscription
explorer-v3-api-polkadot_1      |     async for result in asyncgen:
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/graphql/subscription/map_async_iterator.py", line 60, in __anext__
explorer-v3-api-polkadot_1      |     raise error
explorer-v3-api-polkadot_1      |   File "/usr/src/./app/api/graphql/subscriptions.py", line 162, in subscribe_subscribe_new_event_by_account
explorer-v3-api-polkadot_1      |     latest_event = latest_events.first()
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3429, in first
explorer-v3-api-polkadot_1      |     ret = list(self[0:1])
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
explorer-v3-api-polkadot_1      |     return list(res)
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
explorer-v3-api-polkadot_1      |     cursor.close()
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
explorer-v3-api-polkadot_1      |     compat.raise_(
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
explorer-v3-api-polkadot_1      |     raise exception
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
explorer-v3-api-polkadot_1      |     rows = [proc(row) for row in fetch]
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
explorer-v3-api-polkadot_1      |     rows = [proc(row) for row in fetch]
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 579, in _instance
explorer-v3-api-polkadot_1      |     _populate_full(
explorer-v3-api-polkadot_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
explorer-v3-api-polkadot_1      |     dict_[key] = getter(row)
explorer-v3-api-polkadot_1      |   File "/usr/src/./app/models/field_types.py", line 28, in process
explorer-v3-api-polkadot_1      |     return value.replace(tzinfo=timezone.utc)
explorer-v3-api-polkadot_1      | AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by arjanz** [comment]
Exception when UI calls following graph:

```
# Write your query or mutation here
query { 
  getEventsByAccount( filters: { accountId: "0x9a92efbf31781a4ef54d55d10220a3025f65bed342c53c2b8fc3061f3d09c041" }, pageSize: 100 ) {        
	objects {
	          blockNumber, eventIdx, attributeName, accountId, attributes, pallet, eventName, blockDatetime, sortValue, extrinsicIdx
	}, pageInfo { pageSize, pageNext, pagePrev, blockLimitOffset, blockLimitCount }
}
}
```
