### ISSUE TITLE
 As of 3.10, the *loop* parameter was removed from Lock

### ISSUE THREAD

**Issue by octavei** [polkascan/explorer-api#24]
python version `3.10.0`

**Comment by octavei** [comment]
```
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 832, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 109, in uvloop.loop.run_in_context1
  File "/home/xxx/Desktop/explorer/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 171, in data_received
    self.handle_upgrade()
  File "/home/xxx/Desktop/explorer/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 204, in handle_upgrade
    protocol = self.ws_protocol_class(
  File "/home/xxx/Desktop/explorer/venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 57, in __init__
    super().__init__(ws_handler=self.ws_handler, ws_server=self.ws_server)
  File "/home/xxx/Desktop/explorer/venv/lib/python3.10/site-packages/websockets/server.py", line 103, in __init__
    super().__init__(**kwargs)
  File "/home/xxx/Desktop/explorer/venv/lib/python3.10/site-packages/websockets/protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 77, in __init__
    super().__init__(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary
```

**Comment by octavei** [comment]
command:
```
./start-api.sh
```
